(function(global){
  const ACTION_CLASSES={fold:'fold',call:'call',raise:'raise',jam:'jam',limp:'limp',check:'check'};
  function actionClass(action){const a=String(action).toUpperCase();if(a==='FOLD')return'fold';if(a==='CALL')return'call';if(a==='LIMP')return'limp';if(a==='CHECK')return'check';if(a.startsWith('RAISE'))return'raise';if(a.startsWith('JAM')||a.startsWith('ALL_IN'))return'jam';throw new Error(`unknown action ${action}`);}
  function normalizeStrategy(strategy,tolerance=1e-6){if(!strategy||typeof strategy!=='object')throw new Error('strategy object required');const entries=Object.entries(strategy).filter(([,v])=>Number(v)>0);if(!entries.length)throw new Error('strategy has no positive actions');let sum=0;for(const [action,value] of entries){const v=Number(value);if(!Number.isFinite(v)||v<0||v>1)throw new Error(`invalid frequency for ${action}`);actionClass(action);sum+=v;}if(Math.abs(sum-1)>tolerance)throw new Error(`strategy frequencies sum to ${sum}, expected 1`);return entries.map(([action,value])=>({action,value:Number(value),className:actionClass(action)}));}
  function slices(strategy){const normalized=normalizeStrategy(strategy);let left=0;return normalized.map(item=>{const width=item.value*100;const out={...item,leftPct:left,widthPct:width};left+=width;return out;});}
  function renderCell(cell,label,strategy){cell.innerHTML='';cell.classList.remove('unverified','unreachable');for(const slice of slices(strategy)){const el=document.createElement('span');el.className=`slice action-${slice.className}`;el.style.left=`${slice.leftPct}%`;el.style.width=`${slice.widthPct}%`;el.dataset.action=slice.action;el.dataset.frequency=String(slice.value);cell.appendChild(el);}const text=document.createElement('span');text.className='label';text.textContent=label;cell.appendChild(text);}
  function renderExactCell(cell,label,exactCell){if(!exactCell||typeof exactCell!=='object')throw new Error(`missing exact cell ${label}`);if(Number(exactCell.range_weight)===0){cell.innerHTML='';cell.classList.remove('unverified');cell.classList.add('unreachable');const text=document.createElement('span');text.className='label';text.textContent=label;cell.appendChild(text);return;}if(!Number.isFinite(Number(exactCell.range_weight))||Number(exactCell.range_weight)<=0||Number(exactCell.range_weight)>1)throw new Error(`invalid range_weight for ${label}`);renderCell(cell,label,exactCell.strategy);}
  function validateExactHands(hands,handNames){if(!hands||typeof hands!=='object')throw new Error('hands object required');for(const hand of handNames){const c=hands[hand];if(!c)throw new Error(`missing hand ${hand}`);const rw=Number(c.range_weight);if(!Number.isFinite(rw)||rw<0||rw>1)throw new Error(`invalid range_weight ${hand}`);if(rw===0){if(c.strategy!==null)throw new Error(`zero-reach ${hand} must have strategy:null`);}else normalizeStrategy(c.strategy);}const extras=Object.keys(hands).filter(h=>!handNames.includes(h));if(extras.length)throw new Error(`unexpected hand ${extras[0]}`);return true;}
  function validateChart(chart,handNames){if(!chart||typeof chart!=='object')throw new Error('chart object required');for(const hand of handNames){if(!chart[hand])throw new Error(`missing hand ${hand}`);normalizeStrategy(chart[hand]);}const extras=Object.keys(chart).filter(h=>!handNames.includes(h));if(extras.length)throw new Error(`unexpected hand ${extras[0]}`);return true;}
  const api={normalizeStrategy,slices,renderCell,renderExactCell,validateExactHands,validateChart,ACTION_CLASSES,actionClass};if(typeof module!=='undefined'&&module.exports)module.exports=api;global.SpinsGrid=api;
})(typeof window!=='undefined'?window:globalThis);